services:
  couchdb-1:
    extends:
      file: base/base-couchdb.yml
      service: base-couchdb
    container_name: couchdb-one
    ports:
      - "5984:5984"
    volumes:
      - couchdb-vol-1:/opt/couchdb/data
  couchdb-2:  
    extends:
      file: base/base-couchdb.yml
      service: base-couchdb
    container_name: couchdb-two
    ports:
      - "5985:5984"
    volumes:
      - couchdb-vol-2:/opt/couchdb/data
  couchdb-3:
    extends:
      file: base/base-couchdb.yml
      service: base-couchdb
    container_name: couchdb-three
    ports:
      - "5986:5984"
    volumes:
      - couchdb-vol-3:/opt/couchdb/data
  
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - couchdb-network

volumes:
  couchdb-vol-1:
  couchdb-vol-2:
  couchdb-vol-3:
  portainer_data:

networks:
  couchdb-network:
    driver: bridge
