services:
  couchdb-1:
    extends:
      file: base/base-couchdb.yml
      service: base-couchdb
    container_name: couchdb-one
    ports:
      - "5984:5984"
    volumes:
      - couchdb-vol-1:/opt/couchdb/data
  couchdb-2:
    extends:
      file: base/base-couchdb.yml
      service: base-couchdb
    container_name: couchdb-two
    ports:
      - "5985:5984"
    volumes:
      - couchdb-vol-2:/opt/couchdb/data
  couchdb-3:
    extends:
      file: base/base-couchdb.yml
      service: base-couchdb
    container_name: couchdb-three
    ports:
      - "5986:5984"
    volumes:
      - couchdb-vol-3:/opt/couchdb/data

volumes:
  couchdb-vol-1:
  couchdb-vol-2:
  couchdb-vol-3:

networks:
  couchdb-network:
    ipam:
      driver: bridge
      config:
        - subnet: 172.17.0.0/16
          gateway: 172.17.0.1
