version: '3'

services:
  base-couchdb:
    image: couchdb:3.3.2
    container_name: couchdb
    # ports:
    #   - "5984:5984"
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password